services:
  db:
    image: postgres:latest
    restart: unless-stoppped
    ports: 
      - ${WSRS_DATABSE_PORT:-5432}:5432
    environment: 
      POSTGRES_USER: ${WSRS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WSRS_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local